language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  matrix:
    - DJANGO=2.2
    - DJANGO=3.0

install:
  - pip install -r requires.txt
  - pip install Django~=$DJANGO
  - pip install codecov

script:
  - python -m coverage run ./manage.py test -v3
  - python ./setup.py sdist

after_success: codecov
